biblio/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

from contact.views import MessageAddView

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'biblio.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^shelf/', include('shelf.urls', namespace='shelf')),
    url(r'^contact/$', MessageAddView.as_view()),
    url(r'^accounts/', include('allauth.urls')),

    url(r'^$', 'shelf.views.index_view', name='main-page'),
)

shelf/urls.py
from django.conf.urls import patterns, include, url

from shelf.views import AuthorListView, AuthorDetailView, BookListView, BookDetailView

urlpatterns = patterns('',
    url(r'^autorzy/$', AuthorListView.as_view(), name='author-list'),
    url(r'^autorzy/(?P<pk>\d+)/$', AuthorDetailView.as_view(), name='author-detail'),
    url(r'^ksiazki/$', BookListView.as_view(), name='book-list'),
    url(r'^ksiazki/(?P<pk>\d+)/$', BookDetailView.as_view(), name='book-detail'),
)

contact/models.py
from django.db import models

# Create your models here.

class Message(models.Model):
    name = models.CharField(max_length=250)
    email = models.EmailField()
    message = models.TextField()

    def __str__(self):
        return "message from {name}".format(name=self.name)

rental/models.py
from django.db import models
# from django.contrib.auth.models import User -  bardzo podstawowe
from django.conf import settings

from shelf.models import BookItem

from django.utils.timezone import now


class Rental(models.Model):
    who = models.ForeignKey(settings.AUTH_USER_MODEL) # domyślnie 'django.contrib.auth.User'
    what = models.ForeignKey(BookItem)
    # Jedno z dwóch rozwiązań automatycznej daty
    # when = models.DateTimeField(auto_now_add=True)
    when = models.DateTimeField(default=now)
    returned = models.DateTimeField(null=True, blank=True)

    def __str__(self):
        return "{who} - {what}, from {when} - to {ret}".format(who=self.who, what=self.what, when=self.when, ret=self.returned)

shelf/models.py
from django.db import models
from django.utils.translation import ugettext_lazy as _
from django.core.urlresolvers import reverse_lazy

# Create your models here.

class Author(models.Model):
    first_name = models.CharField(_('first name'), max_length=20)
    last_name = models.CharField(_('last_name'), max_length=50)

    def __str__(self):
        return _("{fn} {ln}").format(fn=self.first_name, ln=self.last_name)

    class Meta:
        ordering = ('last_name', 'first_name')
        verbose_name = _('author')
        verbose_name_plural = _('authors')


class Publisher(models.Model):
    name = models.CharField(max_length=70)

    def __str__(self):
        return self.name


class BookCategory(models.Model):
    name = models.CharField(max_length=50)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = _('book category')
        verbose_name_plural = _('book categories')


class Book(models.Model):
    '''
    Coś w rodzaju rękopisu.
    '''
    title = models.CharField(max_length=100)
    authors = models.ManyToManyField(Author)
    categories = models.ManyToManyField(BookCategory)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse_lazy('shelf:book-detail', kwargs={'pk': self.id})


class BookEdition(models.Model):
    '''
    Wydanie danej książki.
    '''
    book = models.ForeignKey(Book, related_name='editions')
    publisher = models.ForeignKey(Publisher)
    date = models.DateField()
    isbn = models.CharField(max_length=17, blank=True)

    def __str__(self):
        return "{book.title}, {publisher.name}".format(book=self.book, publisher=self.publisher)


COVER_TYPES = (
    ('soft', 'Soft'),
    ('hard', 'Hard'),
)

class BookItem(models.Model):
    ''''
    Konkretny egzemplarz.
    '''
    edition = models.ForeignKey(BookEdition)
    catalogue_number = models.CharField(max_length=30)
    cover_type = models.CharField(max_length=4, choices=COVER_TYPES)

    def __str__(self):
        return "{edition}, {cover}".format(edition=self.edition, cover=self.get_cover_type_display())

users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

class BiblioUser(AbstractUser):
    avatar = models.ImageField(upload_to='avatars/', blank=True, null=True)
    phone = models.CharField(max_length=15, blank=True, default='')

contact/forms.py
from django import forms
from .models import Message

class MessageForm(forms.ModelForm):
    class Meta:
        model = Message
        fields = ('name', 'email', 'message')


# W zasadzie to samo co powyzej tylko zrobione bez wykorzystania modelu
# plus przyklad walidacji
class ContactForm(forms.Form):
    name = forms.CharField()
    email = forms.EmailField()
    message = forms.CharField(widget=forms.Textarea())

    def clean_name(self):
        data = self.cleaned_data['name']
        if "D" not in data:
            raise forms.ValidationError("Musisz miec imie zawirajace litere 'D'!")
        return data

contact/views.py
from django.views.generic import DetailView, FormView
from .models import Message
from .forms import MessageForm, ContactForm

# Create your views here.

# class MessageDetailView(DetailView):
#    model = Message

class MessageAddView(FormView):
    form_class = MessageForm
    template_name = 'contact/message_form.html'
    success_url = '/'

    def form_valid(self, form):
        form.save() # bo form jest instancja ModelForm, ktory posiada metode save()
        return super(MessageAddView ,self).form_valid(form)


# To samo co powyzej tylko bez uzycia modelu
'''
class MessageAddView(FormView):
    form_class = ContactForm
    template_name = 'contact/message_form.html'
    success_url = '/'
'''

rental/views.py
from django.shortcuts import render

# Create your views here.

shelf/views.py
from django.shortcuts import render
from django.views.generic import ListView, DetailView, TemplateView
from django.http import HttpResponse
from .models import Author, Book

# Create your views here.

class MainPageView(TemplateView):
    template_name = 'index.html'


index_view = MainPageView.as_view()

class AuthorListView(ListView):
    model = Author


class AuthorDetailView(DetailView):
    model = Author


class BookListView(ListView):
    model = Book


class BookDetailView(DetailView):
    model = Book

users/views.py
from django.shortcuts import render

# Create your views here.

biblio/templates/base.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>{% block title %}tytuł strony{% endblock %}</title>
</head>

<body>

    <div>
    MENU GŁÓWNE: {% if user.is_authenticated %}<a href="{% url 'account_logout' %}">Wyloguj się</a> {% else %}<a href="{% url 'account_login' %}">Zaloguj się</a>, <a href="{% url 'account_signup' %}">Załóż konto</a>{% endif %}
    </div>

    {% block content %}
    {% endblock %}
</body>
</html>

biblio/templates/index.html
{% extends 'base.html' %}

{% block content %}
Strona główna

{% endblock %}

{% block title %}
Strona główna :)
{% endblock %}

contact/templates/contact/message_form.html
{% extends "base.html" %}

{% block content %}
<form method="post">
{% csrf_token %}
    <table>
        {{ form.as_table }}
    </table>
    <button type="submit">Wyslij</button>
</form>
{% endblock %}
</body>
</html>

shelf/templates/shelf/author_detail.html
{% extends "base.html" %}

{% block content %}

    <div><a href="{% url 'shelf:author-list' %}">Powrót do listy autorów</a></div>
    Profil autora: {{ object.last_name }}, {{ object.first_name }}

    <h2>Książki:</h2>
    <ul>
    {% for book in object.book_set.all %}
        <li><a href="{{ book.get_absolute_url }}">{{ book.title }}</a></li>
        <!-- <li><a href="{% url 'shelf:book-detail' pk=book.id %}">{{ book.title }}</a></li> -->
    {% endfor %}
    </ul>

{% endblock %}

shelf/templates/shelf/author_list.html
{% extends 'base.html' %}

{% block content %}

<ul>
{% for author in object_list %}
    <li><a href="{% url 'shelf:author-detail' author.id %}">{{ author.first_name }} {{ author.last_name }}</li>
{% endfor %}
</ul>

{% endblock %}

shelf/templates/shelf/book_detail.html
{% extends "base.html" %}{% load shelf_tags %}

{% block content %}

<a href="{% url 'shelf:book-list' %}">Powrót do listy książek</a>
<h1>{{ object.title }}</h1>

<h2>Wydania:</h2>

{% show_editions object %}

{% endblock %}

shelf/templates/shelf/book_list.html
{% extends "base.html" %}

{% block content %}

<ul>
{% for book in object_list %}
    <li><a href="{% url 'shelf:book-detail' book.id %}">{{ book.title }}</a> - 
        {% for author in book.authors.all %}
            {{ author.first_name }} {{ author.last_name }}
            {% if not forloop.last %},{% endif %}
        {% endfor %}
    </li>
{% endfor %}
</ul>

{% endblock %}

shelf/templates/tags/show_editions.html
{% load shelf_tags %}

<ul>{% for edition in editions %}
<li>{{ edition.date|pub_date }} - {{ edition.publisher.name }}</li>
{% endfor %}</ul>